### ISSUE TITLE
injection fails when RGL is launched with admin mode

### ISSUE THREAD

**Issue by spike10164** [HappinessMP/issues#1]
### Description of the problem

RGS Launcher doesnt launch GTA 4

### Reproduction steps

Check the RGS launcher as admin, then the HappinessMP launcher cant launch or inject itself into the game.
Fix: uncheck the RGS launcher as admin

### Operating system

Windows 10

**Comment by GTA-Lion** [comment]
Thanks for reporting this issue and even providing a solution for it. I was able to reproduce this issue and will add an additional check in the launcher related to this.

**Comment by GTA-Lion** [comment]
An info was added in the latest version, if injection fails because of this.
