### ISSUE TITLE
AZERTY keyboard conflict with chat key

### ISSUE THREAD

**Issue by Exterminator921** [HappinessMP/issues#2]
### Description of the problem

I'm french so i have an AZERTY keyboard, but when I press z to walk forward, it also starts the chat

### Reproduction steps

put you keyboard layout on azerty and then try to walk forward

### Operating system

Windows 11

**Comment by GTA-Lion** [comment]
Thanks for reporting this issue. The issue is reproducible and will be fixed in the next version.

**Comment by GTA-Lion** [comment]
The default chat key was changed to Y in last build. This should fix the problem.
