### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by DaniilVC** [HappinessMP/issues#3]
### How did the crash occur?

When I am played on server №2

### Has the same crash happened multiple times?

- [ ] Yes
- [x] No

### Attach required files

[1dfbde13-4c4b-4f1f-82ae-725c1daadefe.zip](https://github.com/HappinessMP/issues/files/10482229/1dfbde13-4c4b-4f1f-82ae-725c1daadefe.zip)

### Operating system

Windows 10

**Comment by GTA-Lion** [comment]
Thanks for reporting this crash. I am currently trying to research it.

I still need from you the `core.log` from the logs folder in the HappinessMP directory.

**Comment by GTA-Lion** [comment]
Unfortunately, not enough information was provided to further investigate the issue. Nevertheless, it was most likely fixed with the last update (see changelog in Discord).
