### ISSUE TITLE
Enter (?)

### ISSUE THREAD

**Issue by Exterminator921** [HappinessMP/issues#4]
### How did the crash occur?

The game seems to crash when I press enter

### Has the same crash happened multiple times?

- [X] Yes
- [ ] No

### Attach required files

Well it just closes

### Operating system

Windows 11

**Comment by GTA-Lion** [comment]
Thanks for reporting this issue. But I need more information to fix it.

Where exactly do you press Enter and it crashes? At startup of the game or while being in-game or while chatting, ..?

**Comment by Exterminator921** [comment]
Everywhere, the it only doesn't crash when i'm typing a message

**Comment by GTA-Lion** [comment]
The information provided is not sufficient to reproduce and resolve the problem.
