### ISSUE TITLE
Can't even get into the multiplayer

### ISSUE THREAD

**Issue by HarGabt** [HappinessMP/issues#7]
### Description of the problem

The game simply doesn't, I don't know how to describe it.
![изображение](https://user-images.githubusercontent.com/44652400/214109106-76f853bf-f749-49d0-b753-65d6e941a603.png)

![изображение](https://user-images.githubusercontent.com/44652400/214108960-8b144cfb-36d9-4286-ab22-54592f2f89af.png)

### Reproduction steps

1) Own the game on Steam
2) Join the server with HappinessMP launcher
3) RGL pops up, asks to run the game via Steam
4) Run it
5) Get either episodes selection screen or `Connection to servers failed. Please try again later.`

### Operating system

Windows 11 22H2

**Comment by GTA-Lion** [comment]
Thanks for reporting this issue. Please upload your `launcher.log` and `core.log` file in the logs folder of the HappinessMP directory.

**Comment by HarGabt** [comment]
[core.log](https://github.com/HappinessMP/issues/files/10482642/core.log)
[launcher.log](https://github.com/HappinessMP/issues/files/10482643/launcher.log)

**Comment by GTA-Lion** [comment]
The issue is caused by placing HappinessMP in OneDrive. Please place it somewhere else on your computer.
