### ISSUE TITLE
HappinessMP window doesn't show up.

### ISSUE THREAD

**Issue by i57331** [HappinessMP/issues#8]
### Description of the problem

When I start HappinessMP, the window for it doesn't show up.

### Reproduction steps

Try to start HappinessMP on some setups, this will happen.

### Operating system

Windows 11

**Comment by GTA-Lion** [comment]
Thanks for reporting this issue. Please add the following informations:

- path to your HappinessMP directory
- `launcher.log` & `cef.log` from the logs folder in your HappinessMP directory
- a screenshot of the issue

**Comment by i57331** [comment]
Path is "E:\Programs\HappinessMP".

Logs:
[cef.log](https://github.com/HappinessMP/issues/files/10483201/cef.log)
[launcher.log](https://github.com/HappinessMP/issues/files/10483202/launcher.log)

Screenshot:
![explorer_70wCK3bwyl](https://user-images.githubusercontent.com/14180195/214137369-06df0f3c-b53c-43cd-b76b-94b44bb930ed.jpg)

**Comment by Akmaster95** [comment]
Having the same issue

**Comment by GTA-Lion** [comment]
This issue has been fixed with the latest update after consulting the OP on Discord.
